### ISSUE TITLE
Docker Image instead of `test/deps.sh`

### ISSUE THREAD

**Issue by TG9541** [larsbrinkhoff/xForth#39]
I'm trying to build a Docker image that contains the dependencies in `test/deps.sh`. However, I fail to understand the environment dependencies:
```
root@4481fedadce4:/xForth.git/trunk# sh -e test/deps.sh
+ install_lbforth
+ test -f /root/bin/forth
+ cd lbForth
test/deps.sh: 5: cd: can't cd to lbForth
```
I guess that this has is related with a Travis-CI environment dependency (`$HOME`). Help in understanding the assumptions and dependencies of `test/deps.sh` would be appreciated!

**Comment by larsbrinkhoff** [comment]
I think it's just that you haven't initialized the submodules.  Travis does this by default.

    git submodule update --init

**Comment by larsbrinkhoff** [comment]
I added a submodule update to the deps.sh script: #43.  I think that should help.
